<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-make-appointment</name>
   <tag></tag>
   <elementGuidId>fffa05f3-1c98-4919-b471-3471f74f1333</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;btn-make-appointment&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btn-make-appointment&quot;]</value>
      <webElementGuid>89b0a7de-8611-4ef1-9629-64484a6b70fa</webElementGuid>
   </webElementProperties>
</WebElementEntity>
