<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-login</name>
   <tag></tag>
   <elementGuidId>2fd0b63f-f0d6-4d40-afba-1d01d6144290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;btn-login&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btn-login&quot;]</value>
      <webElementGuid>05ca6cc7-9d61-4444-9d55-e84c9a966a1c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
